//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpareParts.Explorer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpareParts.Explorer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Add_16x16 {
            get {
                object obj = ResourceManager.GetObject("Add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add32x32 {
            get {
                object obj = ResourceManager.GetObject("add32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AllowUsersToEditRanges_16x16 {
            get {
                object obj = ResourceManager.GetObject("AllowUsersToEditRanges_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bag16x16 {
            get {
                object obj = ResourceManager.GetObject("bag16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barcode_32 {
            get {
                object obj = ResourceManager.GetObject("barcode_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap barcode_64 {
            get {
                object obj = ResourceManager.GetObject("barcode_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy {
            get {
                object obj = ResourceManager.GetObject("boy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_128 {
            get {
                object obj = ResourceManager.GetObject("boy_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_32 {
            get {
                object obj = ResourceManager.GetObject("boy_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy_64 {
            get {
                object obj = ResourceManager.GetObject("boy_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap boy48 {
            get {
                object obj = ResourceManager.GetObject("boy48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap brand_new_car_with_dollar_price_tag32x32 {
            get {
                object obj = ResourceManager.GetObject("brand_new_car_with_dollar_price_tag32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy / Deposit.
        /// </summary>
        internal static string BuyDepositProduct {
            get {
                return ResourceManager.GetString("BuyDepositProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_32 {
            get {
                object obj = ResourceManager.GetObject("car_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_64 {
            get {
                object obj = ResourceManager.GetObject("car_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Car_Machine32x32 {
            get {
                object obj = ResourceManager.GetObject("Car_Machine32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Car_Machine64x64 {
            get {
                object obj = ResourceManager.GetObject("Car_Machine64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_model32x32 {
            get {
                object obj = ResourceManager.GetObject("car_model32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap car_model64x64 {
            get {
                object obj = ResourceManager.GetObject("car_model64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CarChangingLanes {
            get {
                object obj = ResourceManager.GetObject("CarChangingLanes", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cart_32 {
            get {
                object obj = ResourceManager.GetObject("cart_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cart_64 {
            get {
                object obj = ResourceManager.GetObject("cart_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cart16x16 {
            get {
                object obj = ResourceManager.GetObject("cart16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cash_register64 {
            get {
                object obj = ResourceManager.GetObject("cash-register64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Complaint_64 {
            get {
                object obj = ResourceManager.GetObject("Complaint_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_32 {
            get {
                object obj = ResourceManager.GetObject("customer_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Customer_32x32 {
            get {
                object obj = ResourceManager.GetObject("Customer_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_64 {
            get {
                object obj = ResourceManager.GetObject("customer_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_add_16 {
            get {
                object obj = ResourceManager.GetObject("customer_add_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_add_32 {
            get {
                object obj = ResourceManager.GetObject("customer_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_add_48 {
            get {
                object obj = ResourceManager.GetObject("customer_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_search_128 {
            get {
                object obj = ResourceManager.GetObject("customer_search_128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_search_32 {
            get {
                object obj = ResourceManager.GetObject("customer_search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap customer_search_64 {
            get {
                object obj = ResourceManager.GetObject("customer_search_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap delete32x32 {
            get {
                object obj = ResourceManager.GetObject("delete32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engine {
            get {
                object obj = ResourceManager.GetObject("engine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engine_32x32_green {
            get {
                object obj = ResourceManager.GetObject("engine_32x32_green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap engine32x32 {
            get {
                object obj = ResourceManager.GetObject("engine32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Engine32x32Blue {
            get {
                object obj = ResourceManager.GetObject("Engine32x32Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a search criteria.
        /// </summary>
        internal static string Error_AtLEastOneCriteriaRequired {
            get {
                return ResourceManager.GetString("Error_AtLEastOneCriteriaRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a customer type.
        /// </summary>
        internal static string Error_CustomerTypeMandatory {
            get {
                return ResourceManager.GetString("Error_CustomerTypeMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide an email address.
        /// </summary>
        internal static string Error_EmailMandatory {
            get {
                return ResourceManager.GetString("Error_EmailMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill the selling and advance amounts..
        /// </summary>
        internal static string Error_FillAmounts {
            get {
                return ResourceManager.GetString("Error_FillAmounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill a {0} number..
        /// </summary>
        internal static string Error_FillNumber {
            get {
                return ResourceManager.GetString("Error_FillNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a first name.
        /// </summary>
        internal static string Error_FirstNameMandatory {
            get {
                return ResourceManager.GetString("Error_FirstNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a last name.
        /// </summary>
        internal static string Error_LastNameMandatory {
            get {
                return ResourceManager.GetString("Error_LastNameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide the mandatory informations, marked with a *.
        /// </summary>
        internal static string Error_MandatoryFields {
            get {
                return ResourceManager.GetString("Error_MandatoryFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a mobile number.
        /// </summary>
        internal static string Error_MobileMandatory {
            get {
                return ResourceManager.GetString("Error_MobileMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a replacement product..
        /// </summary>
        internal static string Error_SelectReplacementProduct {
            get {
                return ResourceManager.GetString("Error_SelectReplacementProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an item.
        /// </summary>
        internal static string Error_SelectRow {
            get {
                return ResourceManager.GetString("Error_SelectRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error_Title {
            get {
                return ResourceManager.GetString("Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem when deleting the item.
        /// </summary>
        internal static string Error_UnableToDelete {
            get {
                return ResourceManager.GetString("Error_UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to confirm the selling, please try again later..
        /// </summary>
        internal static string Error_UnableToSellProduct {
            get {
                return ResourceManager.GetString("Error_UnableToSellProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap find_replace_64 {
            get {
                object obj = ResourceManager.GetObject("find_replace_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home_32x32 {
            get {
                object obj = ResourceManager.GetObject("Home_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Home16x16 {
            get {
                object obj = ResourceManager.GetObject("Home16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap home32x32 {
            get {
                object obj = ResourceManager.GetObject("home32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap location_pin32x32 {
            get {
                object obj = ResourceManager.GetObject("location_pin32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LocationPin {
            get {
                object obj = ResourceManager.GetObject("LocationPin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        internal static string ManagementBrands {
            get {
                return ResourceManager.GetString("ManagementBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string ManagementCategories {
            get {
                return ResourceManager.GetString("ManagementCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Locations.
        /// </summary>
        internal static string ManagementLocations {
            get {
                return ResourceManager.GetString("ManagementLocations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Models.
        /// </summary>
        internal static string ManagementModels {
            get {
                return ResourceManager.GetString("ManagementModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Types.
        /// </summary>
        internal static string ManagementProductTypes {
            get {
                return ResourceManager.GetString("ManagementProductTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratings.
        /// </summary>
        internal static string ManagementRatings {
            get {
                return ResourceManager.GetString("ManagementRatings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories.
        /// </summary>
        internal static string ManagementSubCategories {
            get {
                return ResourceManager.GetString("ManagementSubCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories Level 1.
        /// </summary>
        internal static string ManagementSubCategories1 {
            get {
                return ResourceManager.GetString("ManagementSubCategories1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Categories Level 2.
        /// </summary>
        internal static string ManagementSubCategories2 {
            get {
                return ResourceManager.GetString("ManagementSubCategories2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Models.
        /// </summary>
        internal static string ManagementSubModels {
            get {
                return ResourceManager.GetString("ManagementSubModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string ManagementUsers {
            get {
                return ResourceManager.GetString("ManagementUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mekano16 {
            get {
                object obj = ResourceManager.GetObject("mekano16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mekano200 {
            get {
                object obj = ResourceManager.GetObject("mekano200", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mekano32 {
            get {
                object obj = ResourceManager.GetObject("mekano32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mekano64 {
            get {
                object obj = ResourceManager.GetObject("mekano64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object has been successfully deleted.
        /// </summary>
        internal static string Message_DeleteSuccessfull {
            get {
                return ResourceManager.GetString("Message_DeleteSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Product {0} has been sold to {0}..
        /// </summary>
        internal static string Message_SellingSuccessfull {
            get {
                return ResourceManager.GetString("Message_SellingSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Message_Success {
            get {
                return ResourceManager.GetString("Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer was successfully created.
        /// </summary>
        internal static string Message_SuccessCustomerCreated {
            get {
                return ResourceManager.GetString("Message_SuccessCustomerCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The product was successfully created.
        /// </summary>
        internal static string Message_SuccessProductCreated {
            get {
                return ResourceManager.GetString("Message_SuccessProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The information was successfully updated..
        /// </summary>
        internal static string Message_SuccessProductUpdate {
            get {
                return ResourceManager.GetString("Message_SuccessProductUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} ?.
        /// </summary>
        internal static string MessageDelete_Confirmation {
            get {
                return ResourceManager.GetString("MessageDelete_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} and all its Sub Categories (level 1 and 2) ?.
        /// </summary>
        internal static string MessageDeleteCategory_Confirmation {
            get {
                return ResourceManager.GetString("MessageDeleteCategory_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} and all its Cities ?.
        /// </summary>
        internal static string MessageDeleteCountry_Confirmation {
            get {
                return ResourceManager.GetString("MessageDeleteCountry_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete {0} and all its Sub Models ?.
        /// </summary>
        internal static string MessageDeleteModel_Confirmation {
            get {
                return ResourceManager.GetString("MessageDeleteModel_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to disable this user {0} ?.
        /// </summary>
        internal static string MessageDisable_Confirmation {
            get {
                return ResourceManager.GetString("MessageDisable_Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewCarWithPriceTag {
            get {
                object obj = ResourceManager.GetObject("NewCarWithPriceTag", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer.
        /// </summary>
        internal static string NewCustomerPanelTitle {
            get {
                return ResourceManager.GetString("NewCustomerPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap percentage {
            get {
                object obj = ResourceManager.GetObject("percentage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PistonsCross {
            get {
                object obj = ResourceManager.GetObject("PistonsCross", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PriceTag16x16 {
            get {
                object obj = ResourceManager.GetObject("PriceTag16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_add_32 {
            get {
                object obj = ResourceManager.GetObject("product_add_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_add_48 {
            get {
                object obj = ResourceManager.GetObject("product_add_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap product_add_64 {
            get {
                object obj = ResourceManager.GetObject("product_add_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purchase_order_64 {
            get {
                object obj = ResourceManager.GetObject("purchase_order_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rearrange {
            get {
                object obj = ResourceManager.GetObject("rearrange", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap return_64 {
            get {
                object obj = ResourceManager.GetObject("return_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Search_Product_64 {
            get {
                object obj = ResourceManager.GetObject("Search_Product_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Customer.
        /// </summary>
        internal static string SearchCustomerPanelTitle {
            get {
                return ResourceManager.GetString("SearchCustomerPanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Product.
        /// </summary>
        internal static string SearchProductPanetTitle {
            get {
                return ResourceManager.GetString("SearchProductPanetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SettingsForCategories {
            get {
                object obj = ResourceManager.GetObject("SettingsForCategories", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star_black_32 {
            get {
                object obj = ResourceManager.GetObject("star_black_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap star_black_64 {
            get {
                object obj = ResourceManager.GetObject("star_black_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Product Buying.
        /// </summary>
        internal static string Title_BuyProduct {
            get {
                return ResourceManager.GetString("Title_BuyProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano -Please confirm.
        /// </summary>
        internal static string Title_ConfirmAction {
            get {
                return ResourceManager.GetString("Title_ConfirmAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - New Customer.
        /// </summary>
        internal static string Title_CreateCustomer {
            get {
                return ResourceManager.GetString("Title_CreateCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Customer Sell.
        /// </summary>
        internal static string Title_CreateCustomerProduct {
            get {
                return ResourceManager.GetString("Title_CreateCustomerProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Details.
        /// </summary>
        internal static string Title_Details {
            get {
                return ResourceManager.GetString("Title_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - New Product Type.
        /// </summary>
        internal static string Title_NewProductType {
            get {
                return ResourceManager.GetString("Title_NewProductType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Complaint.
        /// </summary>
        internal static string Title_ProductComplaint {
            get {
                return ResourceManager.GetString("Title_ProductComplaint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Ordering.
        /// </summary>
        internal static string Title_ProductOrdering {
            get {
                return ResourceManager.GetString("Title_ProductOrdering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Replacement.
        /// </summary>
        internal static string Title_ProductReplacement {
            get {
                return ResourceManager.GetString("Title_ProductReplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Request.
        /// </summary>
        internal static string Title_ProductRequest {
            get {
                return ResourceManager.GetString("Title_ProductRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Return.
        /// </summary>
        internal static string Title_ProductReturn {
            get {
                return ResourceManager.GetString("Title_ProductReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Search Customer.
        /// </summary>
        internal static string Title_SearchCustomer {
            get {
                return ResourceManager.GetString("Title_SearchCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mekano - Product Selling.
        /// </summary>
        internal static string Title_SellProduct {
            get {
                return ResourceManager.GetString("Title_SellProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new location.
        /// </summary>
        internal static string TooTip_AddLocation {
            get {
                return ResourceManager.GetString("TooTip_AddLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap touchmode_16x16 {
            get {
                object obj = ResourceManager.GetObject("touchmode_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trademark {
            get {
                object obj = ResourceManager.GetObject("trademark", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trailer {
            get {
                object obj = ResourceManager.GetObject("trailer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trailer64x64 {
            get {
                object obj = ResourceManager.GetObject("trailer64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap two_cogwheels32x32 {
            get {
                object obj = ResourceManager.GetObject("two_cogwheels32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap twocogwheels {
            get {
                object obj = ResourceManager.GetObject("twocogwheels", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_arrow128x128 {
            get {
                object obj = ResourceManager.GetObject("user_arrow128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_arrow32x32 {
            get {
                object obj = ResourceManager.GetObject("user_arrow32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_black_32 {
            get {
                object obj = ResourceManager.GetObject("user_black_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_black_64 {
            get {
                object obj = ResourceManager.GetObject("user_black_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_blue_add2 {
            get {
                object obj = ResourceManager.GetObject("user_blue_add2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_blue_delete {
            get {
                object obj = ResourceManager.GetObject("user_blue_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user_magnifier128x128 {
            get {
                object obj = ResourceManager.GetObject("user_magnifier128x128", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap user32x32 {
            get {
                object obj = ResourceManager.GetObject("user32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserAdd32x32 {
            get {
                object obj = ResourceManager.GetObject("UserAdd32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserAdd64x64 {
            get {
                object obj = ResourceManager.GetObject("UserAdd64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UserGroup_32x32 {
            get {
                object obj = ResourceManager.GetObject("UserGroup_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_black_32 {
            get {
                object obj = ResourceManager.GetObject("users_black_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users_black_64 {
            get {
                object obj = ResourceManager.GetObject("users_black_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap users64x64 {
            get {
                object obj = ResourceManager.GetObject("users64x64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome {0}.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
